### ISSUE TITLE
Update Display controller following the new hardware setup

### ISSUE THREAD

**Issue by rbonghi** [rnanosaur/nanosaur#3]
Now the buses are defined:
* I2C0:
   - Adafruit motor controller
   - LCD0
* I2C1:
   - LCD1

**Comment by FerriteGiant** [comment]
What is the reasoning behind this layout vs something like this one shown below? Seems like it would be easier to daisy chain the displays together? Are you not able to change the i2c address on the displays you are using?

- I2C0
 - Adafruit motor controller
- I2C1
 - LCD0
 - LCD1
