### ISSUE TITLE
camera is not working

### ISSUE THREAD

**Issue by terrylincn** [rnanosaur/nanosaur#34]
it reports: failed to open device 0 in the docker.

**Comment by rbonghi** [comment]
Hi @terrylincn ,

I have many questions for you :-)

* Can you check if `/tmp/argus_socket` exists on your jetson?
* Which camera are you using?
* Have you tried to `nanosaur down` and `nanosaur wakeup` ?

**Comment by terrylincn** [comment]
1. Yes, the /tmp/argus_socket does exists on jetson;
2. I am using a respberry pi camera v2.1
3. tryinng, but after the ops, unable to attach the docker again. :(

**Comment by terrylincn** [comment]
No luck after nanosaur down and nanosaur wakeup. The logs are as following.

nanosaur_camera-4] 1636379530.838665 [0] nanosaur_c: using network interface wlan0 (udp/192.168.31.206) selected arbitrarily from: wlan0, docker0, br-d5bf534a7ce4
[nanosaur_camera-4] [INFO] [1636379530.879149634] [nanosaur_camera]: Frame ID: camera_optical_frame
[nanosaur_camera-4] [INFO] [1636379530.881746982] [nanosaur_camera]: opening camera device 0
[nanosaur_camera-4] [INFO] [1636379530.895378217] [nanosaur_camera]: width 320 height 240 - Framerate 15.000000
[nanosaur_camera-4] [ERROR] [1636379530.945580405] [nanosaur_camera]: failed to open camera device 0
[ERROR] [nanosaur_camera-4]: process has died [pid 172, exit code -11, cmd '/opt/ros_ws/install/nanosaur_camera/lib/nanosaur_camera/nanosaur_camera --ros-args -r __node:=nanosaur_camera -r __ns:=/'].
[INFO] [nanosaur_base-5]: process started with pid [181]

**Comment by rbonghi** [comment]
If you want test only the camera try to do this steps (I don't have right now a self-check)

1. `nanosaur wakeup`
2. `nanosaur stop core`
3. `nanosaur run`

after this step, you will be inside a docker container

1. `ros2 launch nanosaur_camera camera.launch.py`

you will be able to see what happens inside the container

**Comment by rbonghi** [comment]
I'm making huge changes with the camera. The new camera support will be available in https://github.com/rnanosaur/nanosaur_perception

I think will be fixed :-)

**Comment by rbonghi** [comment]
The new release of nanosaur will be deployed soon.
All environment now works with Isaac ROS, I have seen a sensible improvement on my robot, I hope will fix your issue as well :-)

**Comment by rbonghi** [comment]
Fixed :-)
