### ISSUE TITLE
Fix revision number nanosaur install script

### ISSUE THREAD

**Issue by ssheld** [rnanosaur/nanosaur#75]
Nanosaur was updated for jetpack version 4.6.2 in https://github.com/rnanosaur/nanosaur/commit/ffd1f60c3fcad151da1f01a6866df987d3c3366f.

However it seems that in this fix the check for revision number was removed in the nanosaur install script. Specifically in the below image it should concatenate the revision to the version.
<img width="1033" alt="Screen Shot 2022-06-21 at 9 21 21 AM" src="https://user-images.githubusercontent.com/20730278/174809909-1f740cbc-f619-4b11-9055-7418fc77b5c9.png">

**Comment by rbonghi** [comment]
Hi @ssheld 

I found the bug, and now is fixed.

The magic fix is in line 733

```
local JETSON_L4T_RELEASE=$(echo $JETSON_L4T_ARRAY | cut -f1,2 -d '.')
```
